apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: example
resources:
- deployment.yaml
configMapGenerator:
- envs:
  - config.env
  name: config
generators:
- aws-ssm-secret.yaml
